spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: micro-service-config-jaxling-dev
---
spring:
  profiles: test
  application:
    name: micro-service-config-jaxling-test